import localFont from "next/font/local";
import "./globals.css";
// import AdSense from "@/components/Ads/AdSense";
import Script from "next/script";
import Head from "next/head";

// -H 192.168.29.129

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Include the Google Ads script in the Head for proper placement */}
        <meta name="google-adsense-account" content="ca-pub-7147387469181788" />
        <script
          async
          src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7147387469181788`}
          crossOrigin="anonymous"
        ></script>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Script
          async
          src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7147387469181788`}
          crossOrigin="anonymous"
        ></Script> */}
        {children}
      </body>
    </html>
  );
}
